# Generated by Django 5.1.7 on 2025-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=20)),
                ('GENRE', models.CharField(max_length=10)),
                ('RELEASE_DATE', models.DateField()),
                ('RATING', models.FloatField()),
            ],
        ),
    ]
